package guru.nicks.commons.test;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.test.util.TestPropertyValues;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.support.GenericApplicationContext;
import org.testcontainers.mongodb.MongoDBContainer;

/**
 * Runs Mongo (version {@value #IMAGE_TAG}) via TestContainers and sets Spring datasource properties accordingly: URL,
 * driver name etc. (DB name and credentials are generated by the container). Stops container bean when Spring context
 * gets closed.
 * <p>
 * The container is a JVM-wide singleton (reused by context restarts), the replica set URL is exposed via
 * {@link #getReplicaSetUrl()}.
 */
@Slf4j
public class MongoContainerRunner implements ApplicationContextInitializer<GenericApplicationContext> {

    public static final String IMAGE_TAG = "mongo:8.3.8";

    private static final MongoDBContainer CONTAINER = new MongoDBContainer(IMAGE_TAG);

    private static boolean started;

    /**
     * Returns replica set URL of the running container.
     *
     * @return replica set URL, e.g. {@code localhost:32768}
     * @throws IllegalStateException container is not started yet
     */
    public static String getReplicaSetUrl() {
        if (!started) {
            throw new IllegalStateException("Mongo container is not started yet");
        }

        return CONTAINER.getReplicaSetUrl();
    }

    private static MongoDBContainer createAndStartContainer(GenericApplicationContext applicationContext) {
        if (!started) {
            CONTAINER.start();
            started = true;
            log.info("Started Mongo container, replicaSetUrl: {}", CONTAINER.getReplicaSetUrl());
        }

        TestPropertyValues testProps = TestPropertyValues.of(
                "spring.test.database.replace=none",
                // without this, index annotations aren't applied, see
                // https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#new-features.3.0
                "spring.data.mongodb.auto-index-creation=true",
                "spring.data.mongodb.uri=" + CONTAINER.getReplicaSetUrl());

        testProps.applyTo(applicationContext);
        return CONTAINER;
    }

    @Override
    public void initialize(GenericApplicationContext applicationContext) {
        MongoDBContainer container = createAndStartContainer(applicationContext);

        // the only reason to register bean is to stop DB container when app context is closed
        applicationContext.registerBean(MongoDBContainer.class,
                () -> container,
                beanDefinition -> beanDefinition.setDestroyMethodName("stop"));
    }

}
