package guru.nicks.commons.test;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.test.util.TestPropertyValues;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.support.GenericApplicationContext;
import org.testcontainers.containers.JdbcDatabaseContainer;
import org.testcontainers.containers.MySQLContainerProvider;

/**
 * Runs MySQL (version {@value #MYSQL_VERSION}) via TestContainers and sets Spring datasource properties accordingly:
 * URL, driver name etc. (DB name and credentials are generated by the container). Stops container bean when Spring
 * context gets closed.
 * <p>
 * The container is a JVM-wide singleton (reused by context restarts), the JDBC connection URL is exposed via
 * {@link #getJdbcUrl()}.
 */
@Slf4j
public class MySqlContainerRunner implements ApplicationContextInitializer<GenericApplicationContext> {

    public static final String MYSQL_VERSION = "9.3.0";

    private static final JdbcDatabaseContainer<?> CONTAINER = new MySQLContainerProvider().newInstance(MYSQL_VERSION);

    private static boolean started;

    /**
     * Returns JDBC connection URL of the running container.
     *
     * @return JDBC connection URL
     * @throws IllegalStateException container is not started yet
     */
    public static String getJdbcUrl() {
        if (!started) {
            throw new IllegalStateException("MySQL container is not started yet");
        }

        return CONTAINER.getJdbcUrl();
    }

    private static JdbcDatabaseContainer<?> createAndStartContainer(GenericApplicationContext applicationContext) {
        if (!started) {
            CONTAINER.start();
            started = true;
            log.info("Started MySQL container, jdbcUrl: {}", CONTAINER.getJdbcUrl());
        }

        TestPropertyValues testProps = TestPropertyValues.of(
                "spring.test.database.replace=none",
                "spring.datasource.url=" + CONTAINER.getJdbcUrl(),
                "spring.datasource.username=" + CONTAINER.getUsername(),
                "spring.datasource.password=" + CONTAINER.getPassword(),
                "spring.datasource.driver-class-name=" + CONTAINER.getDriverClassName());

        testProps.applyTo(applicationContext);
        return CONTAINER;
    }

    @Override
    public void initialize(GenericApplicationContext applicationContext) {
        JdbcDatabaseContainer<?> container = createAndStartContainer(applicationContext);

        // the only reason to register bean is to stop DB container when app context is closed
        applicationContext.registerBean(JdbcDatabaseContainer.class,
                () -> container,
                beanDefinition -> beanDefinition.setDestroyMethodName("stop"));
    }

}
