package guru.nicks.commons.test;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.test.util.TestPropertyValues;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.support.GenericApplicationContext;
import org.testcontainers.containers.JdbcDatabaseContainer;

/**
 * Runs PostgreSQL (TimescaleDB-HA version {@value TimescaleDbContainerProvider#DEFAULT_IMAGE_TAG}) via TestContainers
 * and sets Spring datasource properties accordingly: URL, driver name, etc. (DB name and credentials are generated by
 * the container dynamically). Stops container bean when Spring context gets closed.
 * <p>
 * The container is a JVM-wide singleton (reused by context restarts), the JDBC connection URL and credentials are
 * exposed via {@link #getJdbcUrl()} / {@link #getUsername()} / {@link #getPassword()}.
 *
 * @see <a href="https://github.com/timescale/timescaledb-docker-ha/">TimescaleDB-HA at Github</a>
 */
@Slf4j
public class PostgreSqlContainerRunner implements ApplicationContextInitializer<GenericApplicationContext> {

    private static final JdbcDatabaseContainer<?> CONTAINER = new TimescaleDbContainerProvider().newInstance(
            TimescaleDbContainerProvider.DEFAULT_IMAGE_TAG);

    private static boolean started;

    /**
     * Returns JDBC connection URL of the running container.
     *
     * @return JDBC connection URL
     * @throws IllegalStateException container is not started yet
     */
    public static String getJdbcUrl() {
        return requireStartedContainer().getJdbcUrl();
    }

    /**
     * Returns the username of the running container (credentials are generated by the container dynamically).
     *
     * @return database username
     * @throws IllegalStateException container is not started yet
     */
    public static String getUsername() {
        return requireStartedContainer().getUsername();
    }

    /**
     * Returns the password of the running container (credentials are generated by the container dynamically).
     *
     * @return database password
     * @throws IllegalStateException container is not started yet
     */
    public static String getPassword() {
        return requireStartedContainer().getPassword();
    }

    /**
     * @return the running container
     * @throws IllegalStateException container is not started yet
     */
    private static JdbcDatabaseContainer<?> requireStartedContainer() {
        if (!started) {
            throw new IllegalStateException("Postgres container is not started yet");
        }

        return CONTAINER;
    }

    private static JdbcDatabaseContainer<?> createAndStartContainer(GenericApplicationContext applicationContext) {
        if (!started) {
            CONTAINER.start();
            started = true;
            log.info("Started Postgres container, jdbcUrl: {}", CONTAINER.getJdbcUrl());
        }

        TestPropertyValues testProps = TestPropertyValues.of(
                "spring.test.database.replace=none",
                "spring.datasource.url=" + CONTAINER.getJdbcUrl(),
                "spring.datasource.username=" + CONTAINER.getUsername(),
                "spring.datasource.password=" + CONTAINER.getPassword(),
                "spring.datasource.driver-class-name=" + CONTAINER.getDriverClassName());

        testProps.applyTo(applicationContext);
        return CONTAINER;
    }

    @Override
    public void initialize(GenericApplicationContext applicationContext) {
        JdbcDatabaseContainer<?> container = createAndStartContainer(applicationContext);

        // the only reason to register bean is to stop DB container when app context is closed
        applicationContext.registerBean(JdbcDatabaseContainer.class,
                () -> container,
                beanDefinition -> beanDefinition.setDestroyMethodName("stop"));
    }

}
