package guru.nicks.commons.test;

import com.redis.testcontainers.RedisContainer;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.test.util.TestPropertyValues;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.support.GenericApplicationContext;

/**
 * Runs Redis (version {@value #IMAGE_TAG}) via TestContainers and sets Spring properties accordingly: host, port
 * (generated by the container dynamically), password, etc. Stops container bean when Spring context gets closed.
 * <p>
 * The container is a JVM-wide singleton (reused by context restarts), the connection URI is exposed via
 * {@link #getRedisUri()}.
 */
@Slf4j
public class RedisContainerRunner implements ApplicationContextInitializer<GenericApplicationContext> {

    public static final String IMAGE_TAG = "redis:8.10.1-alpine";

    private static final RedisContainer CONTAINER = new RedisContainer(IMAGE_TAG);

    private static boolean started;

    /**
     * Returns Redis connection URL of the running container.
     *
     * @return Redis connection URL
     * @throws IllegalStateException container is not started yet
     */
    public static String getRedisUri() {
        if (!started) {
            throw new IllegalStateException("Redis container is not started yet");
        }

        return CONTAINER.getRedisURI();
    }

    private static RedisContainer createAndStartContainer(GenericApplicationContext applicationContext) {
        if (!started) {
            CONTAINER.start();
            started = true;
            log.info("Started Redis container, connectin URI: {}", CONTAINER.getRedisURI());
        }

        TestPropertyValues testProps = TestPropertyValues.of(
                "spring.redis.scheme=redis",
                "spring.redis.trustAnyCertificate=true",
                "spring.redis.connectionMinimumIdleSize=3",
                "spring.redis.database=0",
                "spring.redis.host=" + CONTAINER.getHost(),
                "spring.redis.port=" + CONTAINER.getRedisPort(),
                "spring.redis.password=");

        testProps.applyTo(applicationContext);
        return CONTAINER;
    }

    @Override
    public void initialize(GenericApplicationContext applicationContext) {
        RedisContainer container = createAndStartContainer(applicationContext);

        // the only reason to register bean is to stop DB container when app context is closed
        applicationContext.registerBean(RedisContainer.class,
                () -> container,
                beanDefinition -> beanDefinition.setDestroyMethodName("stop"));
    }

}
